### ISSUE TITLE
关于batch化的问题

### ISSUE THREAD

**Issue by SUDA-HLT-ywfang** [liuwei1206/CCW_NER#2]
您好：
       我看见您代码里注释道：目前仅支持batch_size=1进行训练。想问一下为什么（是哪个部分的问题）？

**Comment by liuwei1206** [comment]
您好，我的模型可以使用任意batch_size进行训练，并不仅仅是batch_size=1，这可能是一个错误的注释，我去将其更正！

另外有一些任务，比如说微博数据集，的确是batch_size=1的时候才能取得最佳效果，batch_size其实和数据集有关！
