### ISSUE TITLE
您好，ontonotes4的数据我申请到了，可是拿不出NER的data

### ISSUE THREAD

**Issue by AigcChangeWorld** [liuwei1206/CCW_NER#3]
正在研究中文NER的方法，研究了一下您的方法，遇到了ontonotes的数据问题，不知道能否发给我一份分隔好的ontonotes4数据。另外您的模型，在MSRA数据集上我有些一些问题想请教。
不知能否添加qq或微信，感激不尽。

**Comment by liuwei1206** [comment]
您好，很抱歉回复完了。我最近特别忙，所以一直没有看到。

我很乐意和您交流，您可以将qq号留在这里，我到时候会添加你。不过，我可能会晚一些添加，因为最近真的太忙了，抱歉。

**Comment by AigcChangeWorld** [comment]
我的qq是535820078，感谢您的回复

**Comment by AigcChangeWorld** [comment]
> 您好，很抱歉回复完了。我最近特别忙，所以一直没有看到。
> 
> 我很乐意和您交流，您可以将qq号留在这里，我到时候会添加你。不过，我可能会晚一些添加，因为最近真的太忙了，抱歉。

我的qq是535820078，感谢您的回复

**Comment by Deonmi** [comment]
同求一份ontonotes4数据集，我的qq是3231117227@qq.com,感激不尽

**Comment by Tan-630** [comment]
您好，同求一份ontonotes4数据集，我的qq是2292983010，感激不尽

**Comment by m-Clown** [comment]
您好，同求一份ontonotes4数据集，qq是534151378，感激不尽

**Comment by agrass1314a** [comment]
您好，求一份ontonotes4处理好的数据集或者是预处理程序，qq是2825438757。下图为ontonotes4的文件，但不知道怎么处理。
<img width="454" alt="ontonotes" src="https://github.com/liuwei1206/CCW-NER/assets/117837979/08b599ac-e837-4fd9-a047-2416624e3812">
