### ISSUE TITLE
您好，请问这个实验中的msra数据和ontonote4数据的划分情况可以详细说说吗？

### ISSUE THREAD

**Issue by one-tree** [liuwei1206/CCW_NER#4]
您好，我们团队最近也在研究命名实体，参考您的代码，我们在MSRA和ontonote4数据上进行复现。
MSRA是使用的划分好的train集和test集，ontonote4数据我们是从LDC官网上下载下来，按照您参考的论文来进行划分的，但是不太清楚是否和您使用的数据一样。
如果方便的话，请问是否可以加个联系方式交流交流呢？非常感谢！

**Comment by AigcChangeWorld** [comment]
请问您的数据从数据库中导出了是吗

**Comment by one-tree** [comment]
是处理成代码需要的形式了

**Comment by liuwei1206** [comment]
Hi，你们好！

很抱歉回复晚了，欢迎交流，有什么需要帮助的可以邮件联系，论文上有我的邮箱地址！
