### ISSUE TITLE
您好 我想问一下 关于每个词对应的word的数量

### ISSUE THREAD

**Issue by xuanzebi** [liuwei1206/CCW_NER#8]
![image](https://user-images.githubusercontent.com/26642184/74209523-0a198600-4cc3-11ea-8bd8-d53934e764dd.png)
如上图，怎么确定每个字符的word数量，
比如南京市长江大桥，对于桥这个字符，有长江大桥，大桥这两个word，对于字符‘市’，只有 南京市一个word, 如何确定每一个batch中的word数量Si^p。

然后就是想问这个数量是规定好的吗还是怎么得出来的

**Comment by liuwei1206** [comment]
您好，这是在数据处理阶段实现已经整理好了，相当于数据预处理部分
